name: Remote ssh command master
on: 
  push:
      # Sequence of patterns matched against refs/heads
      branches:    
        - master         # Push events on master branch
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: /home/gonzalo/scripts/sc-deploy.sh
